### PR TITLE
Add: Button Component

### PR DESCRIPTION
**Pull request by bmendhe23**

### CODE REVIEW

**Review by sakshi006 — COMMENTED** [review]
Looks good.

**Comment by Koushith** [comment]
LGTM.  while opening a PR, you can add a few sentences describing the overall goals of the PR.

ex- what was changed, feature, or component description.

**Comment by bmendhe23** [comment]
> 

Sure will do that from next time @Koushith Thank you. 😄

**Review by Koushith — APPROVED** [review]
LGTM. you can merge this PR

**Pull request merged**
