### PR TITLE
Add: Rating and Snackbar

### PR DESCRIPTION
**Pull request by bmendhe23**
## Description
Feat: 
1. Added Rating and Snackbar component.

Updated:
1. Updated sidebar links for all components.

## Screenshot
ss1
ss2

## Platform tested
- [✔️] Large
- [❌] Tablet
- [❌] Mobile

### CODE REVIEW

**Review by arulk8 — APPROVED** [review]
The code looks clean and neat. my suggestion would be to add author, description meta tags.

**Comment by bmendhe23** [comment]
> The code looks clean and neat. my suggestion would be to add author, description meta tags.

Sure will do that @arulk8 thank you

**Comment by krgarima** [comment]
1. The site looks neat and clean.
2. The only thing I noticed is that write good commit messages. 
You can refer this link https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/

**Comment by TusharJade** [comment]
Looks good to me👍

**Comment by bmendhe23** [comment]
> 1. The site looks neat and clean.
> 2. The only thing I noticed is that write good commit messages. 
> You can refer this link https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/

Thank you @krgarima . sure will look into it.

**Comment by bmendhe23** [comment]
> Looks good to me👍

Thank you @TusharJade

**Review by sakshi006 — APPROVED** [review]
Looks good to me!

**Pull request merged**
