### PR TITLE
Add: Card Component

### PR DESCRIPTION
**Pull request by bmendhe23**
## Description
Added the Card Component to the documentation page with examples and code.

## Screenshot
ss1
ss2
ss3

## Platform tested
- [✅] Large
- [❌] Tablet
- [❌] Mobile

### CODE REVIEW

**Review by sumitch29 — APPROVED** [review]
Card button not working from sidebar

**Comment by bmendhe23** [comment]
> ✔️ Deploy Preview for _onyx-ui_ ready!
> 
> 🔨 Explore the source changes: [022ce77](https://github.com/bmendhe23/OnyxUI/commit/022ce770757fa813161bd4fc270b075c20ef2c61)
> 
> 🔍 Inspect the deploy log: https://app.netlify.com/sites/onyx-ui/deploys/61fa7c9e07d37000083fde75
> 
> 😎 Browse the preview: https://deploy-preview-7--onyx-ui.netlify.app/components/card/card



> Card button not working from sidebar

Thank you @sumitch29 I will add the link.

**Comment by harshitpaliwal95** [comment]
Looks good

**Comment by bmendhe23** [comment]
@harshitpaliwal95 thank you 😄

**Review by harshitpaliwal95 — COMMENTED** [review]
looks good to me

**Pull request merged**
