### PR TITLE
Alert Component

### PR DESCRIPTION
**Pull request by bmendhe23**

### CODE REVIEW

**Review by Asuraking1n — COMMENTED** [review]
Looks good to me, you can use right padding it will be good

**Comment by bmendhe23** [comment]
> Looks good to me, you can use right padding it will be good

thank you @Asuraking1n and sure I will add the padding 😄

**Review by Pratham82 — COMMENTED** [review]
Looks good to me. One link missing from the Badge to alert component.

**Comment by bmendhe23** [comment]
> Looks good to me. One link missing from the Badge to alert component.

thank you @Pratham82 
I will add the link.

**Pull request merged**
