### PR TITLE
Created Avatar

### PR DESCRIPTION
**Pull request by bmendhe23**

### CODE REVIEW

**Comment by sakshi006** [comment]
Looks good to me.

**Review by sakshi006 — COMMENTED** [review]
Looks good to me.

**Review by Asuraking1n — COMMENTED** [review]
Looks good

**Comment by bmendhe23** [comment]
@sakshi006 @Asuraking1n thank you guys for reviewing my PR.

**Review by harshitpaliwal95 — COMMENTED** [review]
perfect ☑️

**Comment by bmendhe23** [comment]
@harshitpaliwal95 thank you 🙂

**Pull request merged**
